### ISSUE TITLE
Twitch Alerts bot is offline

### ISSUE THREAD

**Issue by Sarvagon** [Harfeur/TwitchAlerts#1]
For several days now, the Twitch Alerts bot is offline and don't work anymore (error message "application is not working" and status down).
![image](https://user-images.githubusercontent.com/63664894/202170506-b640a1ea-4842-486d-9103-bc7f51a0f6e7.png)

![image](https://user-images.githubusercontent.com/63664894/202170592-fefd376d-32de-402d-9c52-fdf9281241f0.png)

**Comment by Harfeur** [comment]
Hi thank you for your report. I've restarted the server where the bot is running, but I forgot to restart the bot 😅
